version: '2'
services:
  mysql:
    environment:
        MYSQL_ROOT_PASSWORD: 123456
    image: "docker.io/mysql:5.6" 
    restart: always
    volumes:
        - /usr/local/docker/mysql:/var/lib/mysql
    ports:
        - "9777:3306"
